services:
  pgsql:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: "password"
      POSTGRES_DB: "bilgreen"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "bilgreen-pgsql:/var/lib/postgresql/data"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - bilgreen-redis:/data

  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  bilgreen-pgsql:
  bilgreen-redis:
