services:
  pgsql:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: "password"
      POSTGRES_DB: "enjoy"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "enjoy-pgsql:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  enjoy-pgsql:
  redis_data:
